import clients from "./clients/index";
import type {
  Client,
  Expires,
  Options,
  Prefix,
  Serializable,
  StoreData,
} from "./types";
import { createId, parse, unix } from "./utils";

class Store<TD extends Serializable = Serializable> {
  PREFIX: Prefix = "";
  EXPIRES: Expires = null;
  promise: Promise<Client> | null;
  client!: Client;
  type: string = "UNKNOWN";

  constructor(
    clientPromise: any = new Map(),
    options: Options = {
      prefix: "",
      expires: null,
    },
  ) {
    this.PREFIX = options.prefix || "";
    this.EXPIRES = parse(options.expires || null);

    this.promise = Promise.resolve(clientPromise).then(async (client) => {
      this.client = this.#find(client);
      this.#validate(this.client);
      this.promise = null;
      await this.client.promise;
      this.type = this.client?.TYPE || this.type;
      return client;
    });
  }

  #find(store: any): Client {
    // Already a fully compliant KV store
    if (store instanceof Store) return store.client;

    // One of the supported ones, so we receive an instance and
    // wrap it with the client wrapper
    for (let client of Object.values(clients)) {
      if ("test" in client && client.test(store)) {
        // Some TS BS
        return new client(store) as Client;
      }
      if ("testKeys" in client && typeof store === "object") {
        if (client.testKeys.every((key) => store[key])) {
          return new client(store) as Client;
        }
      }
    }

    // We get passed a class
    if (
      typeof store === "function" &&
      /^class\s/.test(Function.prototype.toString.call(store))
    ) {
      return new store();
    }

    // A raw one, we just receive the single instance to use directly
    return store;
  }

  #validate(client: Client): void {
    if (!client) throw new Error("No client received");
    if (!client.set || !client.get || !client.iterate) {
      throw new Error("Client should have .get(), .set() and .iterate()");
    }

    // No need to validate the methods
    if (client.HAS_EXPIRATION) return;

    for (let method of ["has", "keys", "values"]) {
      if ((client as any)[method]) {
        const msg = `You can only define client.${method}() when the client manages the expiration.`;
        throw new Error(msg);
      }
    }
  }

  // Check if the given data is fresh or not
  #isFresh(data: any, key?: string): data is StoreData {
    // Should never happen, but COULD happen; schedule it for
    // removal and mark it as stale
    if (!data || typeof data !== "object" || !("value" in data)) {
      return false;
    }

    // It never expires, or it's fresh
    return data.expires === null || data.expires > Date.now();
  }

  // Normalize returns the instance's `prefix` and `expires`
  #expiration(expires?: Expires) {
    // When the options.expires = null, it means we don't want it to expire
    return parse(expires !== undefined ? expires : this.EXPIRES);
  }

  /**
   * Save the data on an autogenerated key, can add expiration as well:
   *
   * ```js
   * const key1 = await store.add("value1");
   * const key2 = await store.add({ hello: "world" });
   * const key3 = await store.add("value3", { expires: "1h" });
   * ```
   *
   * **[→ Full .add() Docs](https://polystore.dev/documentation#add)**
   */
  add(value: TD, options?: Options): Promise<string>;
  add<T extends TD>(value: T, options?: Options): Promise<string>;
  async add<T extends TD = TD>(value: T, options: Options): Promise<string> {
    await this.promise;
    const expires = this.#expiration(options?.expires);
    const prefix = options?.prefix || this.PREFIX;

    // Use the underlying one from the client if found
    if (this.client.add) {
      if (this.client.HAS_EXPIRATION) {
        return this.client.add(prefix, value, expires);
      }

      // In the data we need the timestamp since we need it "absolute":
      return this.client.add(prefix, { expires: unix(expires), value });
    }

    return this.set(createId(), value, { prefix, expires });
  }

  /**
   * Save the data on the given key, can add expiration as well:
   *
   * ```js
   * const key = await store.set("key1", "value1");
   * await store.set("key2", { hello: "world" });
   * await store.set("key3", "value3", { expires: "1h" });
   * ```
   *
   * **[→ Full .set() Docs](https://polystore.dev/documentation#set)**
   */
  set(key: string, value: TD, options?: Options): Promise<string>;
  set<T extends TD>(key: string, value: T, options?: Options): Promise<string>;
  async set<T extends Serializable = TD>(
    key: string,
    value: T,
    options: Options,
  ): Promise<string> {
    await this.promise;
    const expires = this.#expiration(options?.expires);
    const prefix = options?.prefix || this.PREFIX;
    const id = prefix + key;

    // Quick delete
    if (value === null || (typeof expires === "number" && expires <= 0)) {
      return this.del(key);
    }

    // The client manages the expiration, so let it manage it
    if (this.client.HAS_EXPIRATION) {
      await this.client.set<T>(id, value, expires);
      return key;
    }

    // In the data we need the timestamp since we need it "absolute":
    await this.client.set<T>(id, { expires: unix(expires), value });
    return key;
  }

  /**
   * Read a single value from the KV store:
   *
   * ```js
   * const value1 = await store.get("key1");
   * // null (doesn't exist or has expired)
   * const value2 = await store.get("key2");
   * // "value2"
   * const value3 = await store.get("key3");
   * // { hello: "world" }
   * ```
   *
   * **[→ Full .get() Docs](https://polystore.dev/documentation#get)**
   */
  get(key: string): Promise<TD | null>;
  get<T extends TD>(key: string): Promise<T | null>;
  async get<T extends TD = TD>(key: string): Promise<T | null> {
    await this.promise;
    const id = this.PREFIX + key;

    // The client already managed expiration and there's STILL some data,
    // so we can assume it's the raw user data
    if (this.client.HAS_EXPIRATION) {
      const data = (await this.client.get<T>(id)) ?? null;

      // No value; nothing to do/check
      if (data === null) return null;

      return data;
    } else {
      const data = (await this.client.get<T>(id)) ?? null;

      // No value; nothing to do/check
      if (data === null) return null;

      if (!this.#isFresh(data, key)) return null;
      return data.value;
    }
  }

  /**
   * Check whether a key exists or not:
   *
   * ```js
   * if (await store.has("key1")) { ... }
   * ```
   *
   * If you are going to use the value, it's better to just read it:
   *
   * ```js
   * const val = await store.get("key1");
   * if (val) { ... }
   * ```
   *
   * **[→ Full .has() Docs](https://polystore.dev/documentation#has)**
   */
  async has(key: string): Promise<boolean> {
    await this.promise;
    const id = this.PREFIX + key;

    if (this.client.has) {
      return this.client.has(id);
    }

    return (await this.get(key)) !== null;
  }

  /**
   * Remove a single key and its value from the store:
   *
   * ```js
   * const key = await store.del("key1");
   * ```
   *
   * **[→ Full .del() Docs](https://polystore.dev/documentation#del)**
   */
  async del(key: string): Promise<string> {
    await this.promise;
    const id = this.PREFIX + key;

    if (this.client.del) {
      await this.client.del(id);
      return key;
    }

    if (this.client.HAS_EXPIRATION) {
      await this.client.set(id, null, 0);
    } else {
      await this.client.set(id, null);
    }

    return key;
  }

  /**
   * @alias of .del(key: string)
   * Remove a single key and its value from the store:
   *
   * ```js
   * const key = await store.delete("key1");
   * ```
   *
   * **[→ Full .del() Docs](https://polystore.dev/documentation#del)**
   */
  async delete(key: string): Promise<string> {
    return this.del(key);
  }

  /**
   * An iterator that goes through all of the key:value pairs in the client
   *
   * ```js
   * for await (const [key, value] of store) {
   *   console.log(key, value);
   * }
   * ```
   *
   * **[→ Full Iterator Docs](https://polystore.dev/documentation#iterator)**
   */
  [Symbol.asyncIterator](): AsyncGenerator<[string, TD], void, unknown>;
  [Symbol.asyncIterator]<T extends TD>(): AsyncGenerator<
    [string, T],
    void,
    unknown
  >;
  async *[Symbol.asyncIterator]<T extends TD = TD>(): AsyncGenerator<
    [string, T],
    void,
    unknown
  > {
    await this.promise;

    if (this.client.HAS_EXPIRATION) {
      for await (const [name, data] of this.client.iterate<T>(this.PREFIX)) {
        const key = name.slice(this.PREFIX.length);
        yield [key, data];
      }
      return;
    }

    for await (const [name, data] of this.client.iterate<T>(this.PREFIX)) {
      const key = name.slice(this.PREFIX.length);
      if (this.#isFresh(data, key)) {
        yield [key, data.value];
      }
    }
  }

  /**
   * Return an array of the entries, in the [key, value] format:
   *
   * ```js
   * const entries = await store.entries();
   * // [["key1", "value1"], ["key2", { hello: "world" }], ...]
   *
   * // To limit it to a given prefix, use `.prefix()`:
   * const sessions = await store.prefix("session:").entries();
   * ```
   *
   * **[→ Full .entries() Docs](https://polystore.dev/documentation#entries)**
   */
  entries(): Promise<[string, TD][]>;
  entries<T extends TD>(): Promise<[string, T][]>;
  async entries<T extends TD = TD>(): Promise<[string, T][]> {
    await this.promise;
    const trim = (key: string): string => key.slice(this.PREFIX.length);

    // With a native method
    if (this.client.entries) {
      if (this.client.HAS_EXPIRATION) {
        const entries = await this.client.entries<T>(this.PREFIX);
        return entries.map(([k, v]) => [trim(k), v]);
      } else {
        const entries = await this.client.entries<T>(this.PREFIX);
        return entries
          .map(([k, v]) => [trim(k), v] as const)
          .filter(([key, data]) => this.#isFresh(data, key))
          .map(([key, data]) => [key, data.value]);
      }
    }

    // No native method, iterate then
    if (this.client.HAS_EXPIRATION) {
      const list: [string, T][] = [];
      for await (const [k, v] of this.client.iterate<T>(this.PREFIX)) {
        list.push([trim(k), v]);
      }
      return list;
    } else {
      const list: [string, T][] = [];
      for await (const [k, data] of this.client.iterate<T>(this.PREFIX)) {
        if (this.#isFresh(data, trim(k))) {
          list.push([trim(k), data.value]);
        }
      }
      return list;
    }
  }

  /**
   * Return an array of the keys in the store:
   *
   * ```js
   * const keys = await store.keys();
   * // ["key1", "key2", ...]
   *
   * // To limit it to a given prefix, use `.prefix()`:
   * const sessions = await store.prefix("session:").keys();
   * ```
   *
   * **[→ Full .keys() Docs](https://polystore.dev/documentation#keys)**
   */
  async keys(): Promise<string[]> {
    await this.promise;

    if (this.client.keys) {
      const list = await this.client.keys(this.PREFIX);
      if (!this.PREFIX) return list;
      return list.map((k) => k.slice(this.PREFIX.length));
    }

    const entries = await this.entries();
    return entries.map((e) => e[0]);
  }

  /**
   * Return an array of the values in the store:
   *
   * ```js
   * const values = await store.values();
   * // ["value1", { hello: "world" }, ...]
   *
   * // To limit it to a given prefix, use `.prefix()`:
   * const sessions = await store.prefix("session:").values();
   * ```
   *
   * **[→ Full .values() Docs](https://polystore.dev/documentation#values)**
   */
  values(): Promise<TD[]>;
  values<T extends TD>(): Promise<T[]>;
  async values<T extends TD = TD>(): Promise<T[]> {
    await this.promise;

    if (this.client.values) {
      if (this.client.HAS_EXPIRATION) return this.client.values<T>(this.PREFIX);
      const list = await this.client.values<T>(this.PREFIX);
      return list
        .filter((data) => this.#isFresh(data))
        .map((data) => data.value);
    }

    const entries = await this.entries<T>();
    return entries.map((e) => e[1]);
  }

  /**
   * Return an object with the keys:values in the store:
   *
   * ```js
   * const obj = await store.all();
   * // { key1: "value1", key2: { hello: "world" }, ... }
   *
   * // To limit it to a given prefix, use `.prefix()`:
   * const sessions = await store.prefix("session:").all();
   * ```
   *
   * **[→ Full .all() Docs](https://polystore.dev/documentation#all)**
   */
  all(): Promise<Record<string, TD>>;
  all<T extends TD>(): Promise<Record<string, T>>;
  async all<T extends TD = TD>(): Promise<Record<string, T>> {
    const entries = await this.entries<T>();
    return Object.fromEntries(entries);
  }

  /**
   * Create a substore where all the keys are stored with
   * the given prefix:
   *
   * ```js
   * const session = store.prefix("session:");
   * await session.set("key1", "value1");
   * console.log(await session.entries());  // session.
   * // [["key1", "value1"]]
   * console.log(await store.entries());  // store.
   * // [["session:key1", "value1"]]
   * ```
   *
   * **[→ Full .prefix() Docs](https://polystore.dev/documentation#prefix)**
   */
  prefix(prefix: Prefix = ""): Store<TD> {
    const store = new Store<TD>(
      Promise.resolve(this.promise).then(() => this.client),
    );
    store.PREFIX = this.PREFIX + prefix;
    store.EXPIRES = this.EXPIRES;
    return store;
  }

  /**
   * Create a substore where all the keys are stored with
   * the given prefix:
   *
   * ```js
   * const session = store.prefix("session:");
   * await session.set("key1", "value1");
   * console.log(await session.entries());  // session.
   * // [["key1", "value1"]]
   * console.log(await store.entries());  // store.
   * // [["session:key1", "value1"]]
   * ```
   *
   * **[→ Full .prefix() Docs](https://polystore.dev/documentation#prefix)**
   */
  expires(expires: Expires = null): Store<TD> {
    const store = new Store<TD>(
      Promise.resolve(this.promise).then(() => this.client),
    );
    store.EXPIRES = parse(expires);
    store.PREFIX = this.PREFIX;
    return store;
  }

  /**
   * Delete all of the records of the store:
   *
   * ```js
   * await store.clear();
   * ```
   *
   * It's useful for cache invalidation, clearing the data, and testing.
   *
   * **[→ Full .clear() Docs](https://polystore.dev/documentation#clear)**
   */
  async clear(): Promise<void> {
    await this.promise;

    // Some times we want to trigger a clearAll for no prefix, but need
    // to do it manually for prefix, so by having a clearAll and NOT clear()
    // we can do this (e.g. forage)
    if (!this.PREFIX && this.client.clearAll) {
      return this.client.clearAll();
    }

    if (this.client.clear) {
      return this.client.clear(this.PREFIX);
    }

    const keys = await this.keys();
    // Note: this gives trouble of concurrent deletes in the FS
    await Promise.all(keys.map((key) => this.del(key)));
  }

  /**
   * Remove all expired records from the store.
   *
   * ```js
   * await store.prune();
   * ```
   *
   * Only affects stores where expiration is managed by this wrapper.
   */
  async prune(): Promise<void> {
    await this.promise;

    // Clients with native expiration don't need pruning
    if (this.client.HAS_EXPIRATION) return;

    if (this.client.prune) {
      await this.client.prune();
    }
  }

  /**
   * Stop the connection to the store, if any:
   *
   * ```js
   * await session.set("key1", "value1");
   * await store.close();
   * await session.set("key2", "value2");  // error
   * ```
   *
   * **[→ Full .close() Docs](https://polystore.dev/documentation#close)**
   */
  async close(): Promise<void> {
    await this.promise;

    if (this.client.close) {
      return this.client.close();
    }
  }
}

export default function createStore(): Store<Serializable>;
export default function createStore<T extends Serializable = Serializable>(
  client?: any,
  options?: Options,
): Store<T>;
export default function createStore(client?: any, options?: Options): Store {
  return new Store(client, options);
}
export type { Client, Serializable, Store };
